import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const customFont = Inter({ subsets: ["latin"] });

const globalFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the globalFont class to the body */}
      <body className={globalFont.className}>{children}</body>
    </html>
  );
}
